artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Shekharmeena28/zip_datasets/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data_zip
  unzip_dir: artifacts/data_ingestion